### PR TITLE
Use opencv-python-headless for container

### PR DESCRIPTION
**Pull request by rmarquis**
This avoids the potential error for some users:

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### CODE REVIEW

**Comment by dimitri009** [comment]
Hey @rmarquis, @andrptrc  I found the solution this morning when I was trying on another Windows device to see if the problem was with the first one, I got the same error and to solve the issue I added:

     RUN apt update && apt install --yes ffmpeg libsm6 libxext6
Not only in the `Dockerfile` but also in `development.Dockerfile`

**Comment by rmarquis** [comment]
I see. So if I understand correctly, the wrong Dockerfile was used by docker because the `.env` file was loaded with the `ENVIRONMENT=development` set up.

By any chance, do you use some python helper (conda, poetry, ... )? Some of these tools might load the `.env` automatically without user feedback, and would thus bypass the main Dockerfile.

**Comment by andrptrc** [comment]
> I see. So if I understand correctly, the wrong Dockerfile was used by docker because the `.env` file was loaded with the `ENVIRONMENT=development` set up.
> 
> By any chance, do you use some python helper (conda, poetry, ... )? Some of these tools might load the `.env` automatically without user feedback, and would thus bypass the main Dockerfile.

No, if I understand correctly the problem come from the fact that the docker-compose used `development.Dockerfile`and not the Dockerfile. So when you do a docker compose up the apt install does not run

**Comment by rmarquis** [comment]
Yes. I guess what I wanted to say is that the main Dockerfile is indeed not used for soem reason. 

However, on my machine (including on a clean Ubuntu VM), docker compose still uses the main Dockerfile, not developement.Dockerfile, and as such I don't face the problem. I assume the `.env` file is not loaded automatically on my machine, while it might be on @dimitri009's, thus telling Docker compose to use the dev Dockerfile.

I assume a better fix is to also modify the `developement.Dockerfile`? Does it still make sense to use `python-opencv-headless`? Should be we do both, using `-headless` and adjusting `development.Dockerfile` as well?

**Comment by rmarquis** [comment]
I might have identified the source of the problem:

In [vscode documentation](https://code.visualstudio.com/docs/python/environments):

```
By default, the Python extension looks for and loads a file named .env in the current workspace folder, then applies those definitions. The file is identified by the default entry "python.envFile": "${workspaceFolder}/.env" in your user settings (see [General Python settings](https://code.visualstudio.com/docs/python/settings-reference#_general-python-settings)). You can change the python.envFile setting at any time to use a different definitions file.
```

The vscode Python extension loads the `.env` file automatically. I'm not using vscode (using JetBrains' Fleet here) so docker compose will by default use the main dockerfile.
In case @dimitri009 is using vscode, that should explain the different behavior.

**Comment by andrptrc** [comment]
I am not sure about that. The thing is that the normal `Dockerfile` is used only when building the image during deploy. And when you are developing locally, the `docker compose up` will simply use the `development.Dockerfile`. So for me we should just tell in the tutorial to add those packages also in the `development.Dockerfile`, without using the `-headless` package.

**Comment by rmarquis** [comment]
All right. I concede I still have no clue why the behaviour is different here (on two different WSL distro)... I don't know how PyCharm handle .env files, but that might depend on the pipenv/poetry environement used as backend.

I'll update the doc shortly.

**Pull request merged**
